enum stat_e { STRENGHT, AGILITY, STAMINA, INTELLECT, SPIRIT };
enum class_e { WARRIOR, PALADIN, HUNTER, ROGUE, PRIEST, DEATHKNIGHT, SHAMAN, MAGE, WARLOCK, MONK, DRUID};
enum race_e { RACE_NONE = 0, RACE_BEAST, RACE_DRAGONKIN, RACE_GIANT, RACE_HUMANOID, RACE_DEMON, RACE_ELEMENTAL, RACE_NIGHT_ELF, RACE_HUMAN, RACE_GNOME, RACE_DWARF, RACE_DRAENEI, RACE_WORGEN, RACE_ORC, RACE_TROLL, RACE_UNDEAD, RACE_BLOOD_ELF, RACE_TAUREN, RACE_GOBLIN, RACE_PANDAREN, RACE_PANDAREN_ALLIANCE, RACE_PANDAREN_HORDE, RACE_MAX, RACE_UNKNOWN };
enum combat_rating_e {
    RATING_MOD_DODGE,
    RATING_MOD_PARRY,
    RATING_MOD_HIT_MELEE,
    RATING_MOD_HIT_RANGED,
    RATING_MOD_HIT_SPELL,
    RATING_MOD_CRIT_MELEE,
    RATING_MOD_CRIT_RANGED,
    RATING_MOD_CRIT_SPELL,
    RATING_MOD_MULTISTRIKE,
    RATING_MOD_READINESS,
    RATING_MOD_SPEED,
    RATING_MOD_RESILIENCE,
    RATING_MOD_LEECH,
    RATING_MOD_HASTE_MELEE,
    RATING_MOD_HASTE_RANGED,
    RATING_MOD_HASTE_SPELL,
    RATING_MOD_EXPERTISE,
    RATING_MOD_MASTERY,
    RATING_MOD_PVP_POWER,
    RATING_MOD_VERS_DAMAGE,
    RATING_MOD_VERS_HEAL,
    RATING_MOD_VERS_MITIG,
};
enum player_level { MIN = 1, MAX = 100, DEFAULT = 100 };
enum player_race { MIN = 7, MAX = 21 };
enum player_class { MIN = 0, MAX = 10 };
enum raid_size { GROUP = 5, TENMAN = 10, TWENTYFIVEMAN = 25 };